---
version: '3'

services:
  tmp_db:
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    expose:
      - "5432"

  tmp_web:
    build: .
    stdin_open: true
    tty: true
    entrypoint: bash config/setup_app.sh
    # command: bash -c "bundle exec rake db:migrate"
    env_file:
      - ./.env
    volumes:
      - .:/home/app/
    ports:
      - "3000:3000"
    depends_on:
      - tmp_db
